name: 'Journalist'
description: 'Run a command and post the output in the issue'
inputs:
  github-token:
    description: 'the github token'
    required: true
  command:
    description: 'the command line to execute'
    required: true
  keywords:
    description: 'list of keywords when trigger the command'
runs:
  using: 'node12'
  main: 'dist/index.js'
