name: "test-local"
on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - name: execute command
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        keywords: '["#journalist run"]'
        command: echo 'hello world'
